[phases.setup]
nixPkgs = ["git"]
cmds = [
  "git submodule update --init --recursive"
]

[phases.install]
dependsOn = ["setup"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "npx serve -s dist/typedb-studio/browser -l $PORT"
